{% set version = "2.0.5" %}

package:
  name: bob.ip.color
  version: {{ version }}

source:
  fn: bob.ip.color-{{ version }}.zip
  md5: 0a6d2a90ba808a406932c0ba8c7d04b7
  url: https://pypi.io/packages/source/b/bob.ip.color/bob.ip.color-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - cmake
    - pkg-config
    - boost 1.61.*

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.ip.color

  imports:
    - bob
    - bob.ip
    - bob.ip.color

  requires:
    - nose

about:
  home: http://github.com/bioidiap/bob.ip.color
  license: Modified BSD License (3-clause)
  summary: Color Conversion Utilities of Bob

extra:
  recipe-maintainers:
    - 183amir
